### ISSUE TITLE
Create Member class

### ISSUE THREAD

**Issue by freiheit** [freiheit/Bay-Oh-Woolph#1]
- [x] Figure out basic object model
- [x] Build class
- [x] Relate class to database http://pythoncentral.io/introductory-tutorial-python-sqlalchemy/
- [x] Set up stuff to automatically sync back and forth with DB

**Comment by HuntingPhoenix** [comment]
Is there a better way/place for design discussions?

We'll want to track:

- Cmdr Name
- Rank
- Timezone
- Role
- Join Date

Optional additions:

- Email address
- Discord "ID"
- Preferred activities

**Comment by freiheit** [comment]
Check out the "project" tab and "wiki" tab.

For the details of a specific thing, the "Issue" stuff is great, though.

I'm thinking the minimum requirements for initial rollout are:

- Discord id
- Points

The rest is for future features or stuff we can get from Discord API.
